using BddDotNet.Gherkin.SourceGenerator.Models;
using BddDotNet.Gherkin.SourceGenerator.Services;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System.Collections.Immutable;
using System.Text;

namespace BddDotNet.Gherkin.SourceGenerator.Generators;

[Generator]
internal sealed class ScenariosExtensionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var arguments = context.CompilationProvider
            .Select(static (compilation, _) => compilation.Assembly.Name);

        var featureFiles = context.AdditionalTextsProvider
            .Where(static file => Path.GetExtension(file.Path) == ".feature")
            .Collect();

        context.RegisterImplementationSourceOutput(featureFiles.Combine(arguments), GenerateFeatureClass);
    }

    private static void GenerateFeatureClass(SourceProductionContext context, (ImmutableArray<AdditionalText> features, string? assemblyName) args)
    {
        if (args.assemblyName == null)
        {
            return;
        }

        var declarations = GetTestCasesContent(args.assemblyName, args.features);
        var featureClassContent = GetTestClassContent(declarations);
        var formattedFeatureClassContent = FormatCode(featureClassContent);
        context.AddSource($"SourceGeneratedGherkinScenarios.g.cs", formattedFeatureClassContent);
    }
    public static string FormatCode(string code)
    {
        return CSharpSyntaxTree.ParseText(code)
            .GetRoot()
            .NormalizeWhitespace()
            .SyntaxTree
            .GetText()
            .ToString();
    }

    private static string GetTestCasesContent(string assemblyName, ImmutableArray<AdditionalText> features)
    {
        var testCasesParser = new TestCasesParser();

        var result = testCasesParser.Parse(assemblyName, features);
        if (result.Errors.Any())
        {
            var featureErrorsDeclarations = GetParserErrorsDeclarations(result);
            return featureErrorsDeclarations;
        }

        var declarations = GetTestCasesDeclarations(result);

        return declarations;
    }

    private static string GetTestClassContent(string declarations)
    {
        var featureClassContent =
           $$"""
            // <auto-generated/>
            
            #nullable disable warnings

            using BddDotNet;
            using Microsoft.Extensions.DependencyInjection;

            namespace BddDotNet.Gherkin;

            internal static partial class GherkinSourceGeneratorExtensions
            {
                public static partial void SourceGeneratedGherkinScenarios(this IServiceCollection services)
                {
                    {{declarations}}
                }
            }
            """;

        return featureClassContent;
    }

    private static string GetTestCasesDeclarations(TestCaseParserResult testCaseParserResult)
    {
        var declarations = new StringBuilder();

        foreach (var background in testCaseParserResult.Backgrounds)
        {
            declarations.AppendLine(GetBackgroundContent(background));
        }

        foreach (var testCase in testCaseParserResult.TestCases)
        {
            declarations.AppendLine(GetTestCaseContent(testCase));
        }

        return declarations.ToString();
    }

    private static string GetParserErrorsDeclarations(TestCaseParserResult result)
    {
        var declaration = new StringBuilder();

        foreach (var error in result.Errors)
        {
            declaration.AppendLine(
                $$"""
                #line ({{error.Line}}, {{error.Column}})-({{error.Line + 1}}, 1) 12 "{{error.FeatureFilePath}}"
                #error {{error.Message}}
                """);
        }

        declaration.AppendLine("#line default");

        return declaration.ToString();
    }

    private static string GetBackgroundContent(TestCaseBackground background)
    {
        var declaration =
            $$""""
            var background{{background.Index}} = async (BddDotNet.Extensibility.IScenarioContext context) =>
            {
                {{GetTestStepsContent(background.Steps)}}
            };
            """";

        return declaration;
    }

    private static string GetTestCaseContent(TestCase testCase)
    {
        var declaration =
            $$""""
            services.Scenario(
                "{{testCase.AssemblyName}}",
                "{{testCase.AssemblyName}}",
                "{{testCase.Feature}}",
                "{{testCase.Scenario}}",
                """{{testCase.FeaturePath}}""",
                {{testCase.Line}},
                async context =>
                {
                    {{GetTestStepBackgroundContent(testCase)}}
                    {{GetTestStepsContent(testCase.Steps)}}
                });
            """";

        return declaration;
    }

    private static string GetTestStepBackgroundContent(TestCase testCase)
    {
        if (testCase.Background == null)
        {
            return string.Empty;
        }

        var content =
            $"""
            await background{testCase.Background.Index}(context);
            """;

        return content;
    }

    private static string GetTestStepsContent(List<TestCaseStep> steps)
    {
        var stepDeclarations = new StringBuilder();

        foreach (var step in steps)
        {
            stepDeclarations.AppendLine(
                $""""
                #line ({step.Line}, {step.Column})-({step.Line + 1}, 1) 12 "{step.FeaturePath}"
                """");

            if (step.DataTable is { } dataTable)
            {
                stepDeclarations.AppendLine(
                    $$""""
                    await context.{{step.Keyword}}("""{{step.Text}}""", (object)new string[][]
                    {
                        {{GetDataTableContent(dataTable)}}
                    });
                    """");
            }
            else if (step.DocString is string docString)
            {
                stepDeclarations.AppendLine(
                    $$""""
                    await context.{{step.Keyword}}("""{{step.Text}}""",
                    """
                    {{docString}}
                    """);
                    """");
            }
            else
            {
                stepDeclarations.AppendLine(
                    $""""
                    await context.{step.Keyword}("""{step.Text}""");
                    """");
            }
        }

        stepDeclarations.AppendLine("#line default");

        return stepDeclarations.ToString();
    }

    private static string GetDataTableContent(string[][] dataTable)
    {
        var dataTableDeclaration = new StringBuilder();

        foreach (var row in dataTable)
        {
            dataTableDeclaration.Append("new[] {");
            foreach (var cell in row)
            {
                dataTableDeclaration.Append(
                    $""""
                    """{cell}""",
                    """");
            }
            dataTableDeclaration.AppendLine("},");
        }

        return dataTableDeclaration.ToString();
    }
}
