using Microsoft.CodeAnalysis;

namespace BddDotNet.Gherkin.SourceGenerator.Generators;

[Generator]
internal sealed class StepAttributesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context =>
        {
            context.AddSource("GherkinAttributes.cs",
                $$"""
                // <auto-generated/>
                
                #nullable disable warnings

                namespace BddDotNet.Gherkin;

                [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                internal sealed class GivenAttribute(string pattern) : global::System.Attribute
                {
                    public string Pattern { get; } = pattern;
                }
                
                [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                internal sealed class WhenAttribute(string pattern) : global::System.Attribute
                {
                    public string Pattern { get; } = pattern;
                }
                
                [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                internal sealed class ThenAttribute(string pattern) : global::System.Attribute
                {
                    public string Pattern { get; } = pattern;
                }
                """);
        });
    }
}
