using Microsoft.CodeAnalysis;

namespace BddDotNet.Gherkin.SourceGenerator;

[Generator]
internal sealed class ExtensionsClassGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context =>
        {
            context.AddSource("GherkinSourceGeneratorExtensions.cs",
                $$"""
                // <auto-generated/>

                #nullable disable warnings

                using Microsoft.Extensions.DependencyInjection;

                internal static partial class GherkinSourceGeneratorExtensions
                {
                    public static partial void SourceGeneratedGherkinSteps(this IServiceCollection services);
                
                    public static partial void SourceGeneratedGherkinScenarios(this IServiceCollection services);
                }
                """);
        });
    }
}
