using Microsoft.CodeAnalysis;

namespace BddDotNet.Gherkin.SourceGenerator;

[Generator]
internal sealed class GlobalUsingsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context =>
        {
            context.AddSource("GherkinGlobalUsings.g.cs",
                $$"""
                // <auto-generated/>
                
                #nullable disable warnings
                
                global using BddDotNet.Gherkin;
                """);
        });
    }
}