name: Build
on: push

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x
            10.0.x

      - name: Build
        run: dotnet build ./src/BddDotNet.slnx

      - name: .NET Framework Tests
        if: matrix.os == 'windows-latest'
        run: dotnet test -f net472 --no-build --no-restore ./src/BddDotNet.slnx

      - name: .NET 8 Tests
        run: dotnet test -f net8.0 --no-build --no-restore ./src/BddDotNet.slnx

      - name: .NET 9 Tests
        run: dotnet test -f net9.0 --no-build --no-restore ./src/BddDotNet.slnx

      - name: .NET 10 Tests
        run: dotnet test -f net10.0 --no-build --no-restore ./src/BddDotNet.slnx
        
  format-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Format
        run: dotnet format --verify-no-changes ./src/BddDotNet.slnx